// <auto-generated />
namespace E_ComerceSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jj));
        
        string IMigrationMetadata.Id
        {
            get { return "202109221655397_jj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
